# Kết nối MySQL (Thay đổi username/password nếu cần)
spring.datasource.url=jdbc:mysql://localhost:3306/kms_system?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate tự động tạo/cập nhật bảng dựa trên các Class DTO (@Entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Cho phép Hibernate khởi tạo dữ liệu từ file import.sql (nếu có)
spring.sql.init.mode=always