spring.datasource.url=jdbc:mysql://localhost:3306/hr_expert_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
# Cho phép chạy Swing UI trong môi trường Spring
spring.main.headless=false